name: Hello World!

on:
  push:
    branches:
      - '*'

jobs:
  hello_world_job_1:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l


# name: Health check schedule

# on:
#   schedule:
#     - cron: '21 * * * *'

# jobs:
#   health_check:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Check Health
#         run: curl https://full-stack-open-pokedex-urty.onrender.com/health