name: Health check schedule

on:
  schedule:
    - cron: '21 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Health
        run: curl https://full-stack-open-pokedex-urty.onrender.com/health